/**
 * Datos de referencia para el instalador limpio del Core (EstructuraInicialService.js).
 *
 * CABECERAS_HOJA_MVP y CATALOGO_SEMILLA_MVP son una transcripción literal de la hoja
 * de desarrollo real (spreadsheetId 12gIvFzsAXbaXJxFbIq2bjbBpPmtazotdTHkgvfp3Jc0),
 * verificada campo a campo antes de escribir este archivo. No inventar ni reordenar
 * columnas aquí sin volver a verificar contra la hoja real.
 */

var CABECERAS_HOJA_MVP = Object.freeze({
  '01_CAMPANAS': Object.freeze(['ID', 'NOMBRE', 'DESCRIPCION', 'RESPONSABLE_ID', 'FECHA_INICIO_INICIAL', 'FECHA_FIN_INICIAL', 'FECHA_INICIO_PLAN', 'FECHA_FIN_PLAN', 'FECHA_INICIO_REAL', 'FECHA_FIN_REAL', 'ESTADO', 'PORCENTAJE_AVANCE', 'MOTIVO_REPLANIFICACION', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES', 'OBJETIVO', 'RESULTADO_ESPERADO', 'NIVEL_DATO']),
  '02_PROYECTOS': Object.freeze(['ID', 'CAMPANA_ID', 'NOMBRE', 'DESCRIPCION', 'TIPO_PROYECTO', 'PRIORIDAD', 'RESPONSABLE_ID', 'FECHA_INICIO_INICIAL', 'FECHA_FIN_INICIAL', 'FECHA_INICIO_PLAN', 'FECHA_FIN_PLAN', 'FECHA_INICIO_REAL', 'FECHA_FIN_REAL', 'ESTADO', 'PORCENTAJE_AVANCE', 'MOTIVO_REPLANIFICACION', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES', 'OBJETIVO', 'RESULTADO_ESPERADO', 'CRITERIOS_ACEPTACION', 'DEFINITION_OF_DONE', 'VALIDADOR_ID', 'CLIENTE_ID']),
  '03_PRODUCTOS': Object.freeze(['ID', 'CODIGO', 'NOMBRE', 'DESCRIPCION', 'VERSION', 'ORIGEN', 'UNIDAD', 'CANTIDAD_PREVISTA', 'CANTIDAD_PRODUCIDA', 'FECHA_REQUERIDA', 'PRIORIDAD', 'RESPONSABLE_ID', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES', 'OBJETIVO', 'RESULTADO_ESPERADO', 'CRITERIOS_ACEPTACION', 'DEFINITION_OF_DONE', 'VALIDADOR_ID']),
  '04_PROYECTO_PRODUCTO': Object.freeze(['ID', 'PROYECTO_ID', 'PRODUCTO_ID', 'CANTIDAD_ASIGNADA', 'PRIORIDAD', 'FECHA_REQUERIDA', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES', 'MODO_USO']),
  '05_PROCESOS': Object.freeze(['ID', 'PRODUCTO_ID', 'NOMBRE', 'DESCRIPCION', 'ORDEN_SECUENCIA', 'PROCESO_PREDECESOR_ID', 'DURACION_PREVISTA_DIAS', 'DURACION_REAL_DIAS', 'RESPONSABLE_ID', 'FECHA_INICIO_PLAN', 'FECHA_FIN_PLAN', 'FECHA_INICIO_REAL', 'FECHA_FIN_REAL', 'ESTADO', 'PORCENTAJE_AVANCE', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES', 'OBJETIVO', 'RESULTADO_ESPERADO', 'CRITERIOS_ACEPTACION', 'DEFINITION_OF_DONE', 'VALIDADOR_ID', 'PROYECTO_PRODUCTO_ID', 'MODO_USO', 'METODO_CALCULO_AVANCE', 'FASE_PRODUCCION']),
  '06_TAREAS': Object.freeze(['ID', 'PROCESO_ID', 'NOMBRE', 'DESCRIPCION', 'ORDEN_SECUENCIA', 'TAREA_PREDECESORA_ID', 'DURACION_PREVISTA_DIAS', 'DURACION_REAL_DIAS', 'FECHA_INICIO_PLAN', 'FECHA_FIN_PLAN', 'FECHA_INICIO_REAL', 'FECHA_FIN_REAL', 'ESTADO', 'PORCENTAJE_AVANCE', 'MOTIVO_BLOQUEO', 'MOTIVO_POSPOSICION', 'MOTIVO_CANCELACION', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES', 'OBJETIVO', 'RESULTADO_ESPERADO', 'CRITERIOS_ACEPTACION', 'DEFINITION_OF_DONE', 'VALIDADOR_ID', 'METODO_CALCULO_AVANCE']),
  '07_TAREA_RESPONSABLE': Object.freeze(['ID', 'TAREA_ID', 'PERSONA_EQUIPO_ID', 'ROL_ASIGNADO', 'FECHA_INICIO_ASIGNACION', 'FECHA_FIN_ASIGNACION', 'PORCENTAJE_DEDICACION', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '08_MATERIALES': Object.freeze(['ID', 'CODIGO', 'NOMBRE', 'CATEGORIA', 'UNIDAD', 'STOCK_ACTUAL', 'STOCK_MINIMO', 'CANTIDAD_RESERVADA', 'PROVEEDOR', 'PLAZO_REPOSICION_DIAS', 'UBICACION', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES', 'PROVEEDOR_ID']),
  '09_PRODUCTO_MATERIAL': Object.freeze(['ID', 'PRODUCTO_ID', 'MATERIAL_ID', 'CANTIDAD_PREVISTA', 'UNIDAD', 'CANTIDAD_RESERVADA', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '10_TAREA_MATERIAL': Object.freeze(['ID', 'TAREA_ID', 'MATERIAL_ID', 'CANTIDAD_PREVISTA', 'CANTIDAD_CONSUMIDA', 'CANTIDAD_DESPERDICIADA', 'UNIDAD', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES', 'MOTIVO_DESVIACION']),
  '11_PERSONAS_EQUIPOS': Object.freeze(['ID', 'TIPO', 'NOMBRE', 'ROL', 'CAPACIDAD_SEMANAL_DIAS', 'DISPONIBILIDAD', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES', 'EMAIL', 'TELEFONO', 'COORDINADOR_ID']),
  '12_DECISIONES': Object.freeze(['ID', 'PROYECTO_ID', 'TITULO', 'CONTEXTO', 'TIPO', 'RESPONSABLE_ID', 'FECHA_LIMITE', 'ESTADO', 'IMPACTO', 'RESOLUCION', 'FECHA_RESOLUCION', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES', 'OBJETIVO', 'RESULTADO_ESPERADO', 'CRITERIOS_ACEPTACION', 'DEFINITION_OF_DONE', 'VALIDADOR_ID']),
  '13_INCIDENCIAS': Object.freeze(['ID', 'NIVEL_INCIDENCIA', 'CAMPANA_ID', 'PROYECTO_ID', 'PRODUCTO_ID', 'PROCESO_ID', 'TAREA_ID', 'CLIENTE_ID', 'JIRA_KEY', 'JIRA_URL', 'TITULO', 'DESCRIPCION', 'TIPO', 'PRIORIDAD', 'RESPONSABLE_ID', 'FECHA_DETECCION', 'FECHA_LIMITE', 'ESTADO', 'IMPACTO', 'ACCION_CORRECTORA', 'FECHA_RESOLUCION', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '14_DOCUMENTOS': Object.freeze(['ID', 'ENTIDAD_TIPO', 'ENTIDAD_ID', 'TIPO_DOCUMENTO', 'TITULO', 'DESCRIPCION', 'VERSION', 'URL', 'ESTADO', 'FECHA_DOCUMENTO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '15_PROVEEDORES': Object.freeze(['ID', 'CODIGO', 'NOMBRE', 'NIF_CIF', 'PERSONA_CONTACTO', 'EMAIL', 'TELEFONO', 'DIRECCION', 'PLAZO_ENTREGA_DIAS', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '16_ASIGNACION': Object.freeze(['ID', 'ENTIDAD_TIPO', 'ENTIDAD_ID', 'PERSONA_EQUIPO_ID', 'ROL_ASIGNADO', 'FECHA_INICIO_ASIGNACION', 'FECHA_FIN_ASIGNACION', 'PORCENTAJE_DEDICACION', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '17_RELACION': Object.freeze(['ID', 'ENTIDAD_TIPO', 'ENTIDAD_ORIGEN_ID', 'ENTIDAD_DESTINO_ID', 'TIPO_RELACION', 'DESFASE_DIAS', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '18_VINCULO': Object.freeze(['ID', 'ENTIDAD_ORIGEN_TIPO', 'ENTIDAD_ORIGEN_ID', 'ENTIDAD_DESTINO_TIPO', 'ENTIDAD_DESTINO_ID', 'TIPO_VINCULO', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '19_MOVIMIENTO_MATERIAL': Object.freeze(['ID', 'MATERIAL_ID', 'TAREA_ID', 'TIPO_MOVIMIENTO', 'CANTIDAD', 'UNIDAD', 'FECHA_MOVIMIENTO', 'RESPONSABLE_ID', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '20_EJECUCION_TAREA': Object.freeze(['ID', 'TAREA_ID', 'RESPONSABLE_ID', 'FECHA_INICIO', 'FECHA_FIN', 'DURACION_REAL_DIAS', 'ESTADO', 'RESULTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '21_PROVEEDOR_MATERIAL': Object.freeze(['ID', 'PROVEEDOR_ID', 'MATERIAL_ID', 'PRECIO_UNITARIO', 'PLAZO_ENTREGA_DIAS', 'ES_PREFERENTE', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '22_EQUIPO_MIEMBRO': Object.freeze(['ID', 'EQUIPO_ID', 'MIEMBRO_ID', 'ROL_EN_EQUIPO', 'FECHA_ALTA', 'FECHA_BAJA', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '23_RECURSO': Object.freeze(['ID', 'CODIGO', 'NOMBRE', 'DESCRIPCION', 'CLASE_RECURSO', 'CATEGORIA_RECURSO', 'UBICACION_ID', 'RESPONSABLE_ID', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES', 'MODO_COSTE', 'COSTE_ADQUISICION', 'VIDA_UTIL_ANOS', 'COSTE_PERIODICO', 'PERIODICIDAD_COSTE', 'CAPACIDAD', 'CAPACIDAD_UNIDAD']),
  '24_TAREA_RECURSO': Object.freeze(['ID', 'TAREA_ID', 'RECURSO_ID', 'TIPO_USO', 'FECHA_INICIO', 'FECHA_FIN', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '25_PEDIDO_PROVEEDOR': Object.freeze(['ID', 'PROVEEDOR_ID', 'FECHA_PEDIDO', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '26_PEDIDO_PROVEEDOR_LINEA': Object.freeze(['ID', 'PEDIDO_PROVEEDOR_ID', 'MATERIAL_ID', 'CANTIDAD_PEDIDA', 'PRECIO_UNITARIO', 'UNIDAD', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '27_RECEPCION': Object.freeze(['ID', 'PEDIDO_PROVEEDOR_ID', 'FECHA_RECEPCION', 'RESPONSABLE_ID', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '28_RECEPCION_LINEA': Object.freeze(['ID', 'RECEPCION_ID', 'MATERIAL_ID', 'CANTIDAD_RECIBIDA', 'UNIDAD', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '29_HORARIO': Object.freeze(['ID', 'ENTIDAD_TIPO', 'ENTIDAD_ID', 'DIA_SEMANA', 'HORA_INICIO', 'HORA_FIN', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES', 'FECHA_INICIO_VIGENCIA', 'FECHA_FIN_VIGENCIA']),
  '30_PRESUPUESTO': Object.freeze(['ID', 'ENTIDAD_TIPO', 'ENTIDAD_ID', 'CATEGORIA', 'IMPORTE_PREVISTO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '31_FUENTE_FINANCIACION': Object.freeze(['ID', 'ENTIDAD_TIPO', 'ENTIDAD_ID', 'NOMBRE', 'TIPO', 'IMPORTE', 'ESTADO', 'FECHA_SOLICITUD', 'FECHA_RESOLUCION', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES', 'CONVOCATORIA_ID']),
  '32_COSTE': Object.freeze(['ID', 'ENTIDAD_TIPO', 'ENTIDAD_ID', 'CONCEPTO', 'IMPORTE', 'FECHA', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES', 'CATEGORIA']),
  '33_COMPETENCIA': Object.freeze(['ID', 'NOMBRE', 'DESCRIPCION', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '34_PERSONA_COMPETENCIA': Object.freeze(['ID', 'PERSONA_EQUIPO_ID', 'COMPETENCIA_ID', 'NIVEL', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '35_RECURSO_COMPETENCIA': Object.freeze(['ID', 'RECURSO_ID', 'COMPETENCIA_ID', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '36_CONVOCATORIA': Object.freeze(['ID', 'NOMBRE', 'ENTIDAD_CONVOCANTE', 'TIPO', 'IMPORTE_DISPONIBLE', 'IMPORTE_MINIMO_SOLICITUD', 'IMPORTE_MAXIMO_SOLICITUD', 'TIPO_PROYECTO_ELEGIBLE', 'FECHA_LIMITE', 'REQUISITOS', 'URL_BASES', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '37_ETIQUETA_IMPACTO': Object.freeze(['ID', 'ENTIDAD_TIPO', 'ENTIDAD_ID', 'CATEGORIA_IMPACTO', 'DESCRIPCION', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '38_CLIENTE': Object.freeze(['ID', 'CODIGO', 'NOMBRE', 'TIPO_CLIENTE', 'NIF_CIF', 'PERSONA_CONTACTO', 'EMAIL', 'TELEFONO', 'DIRECCION', 'RESPONSABLE_CUENTA_ID', 'ESTADO', 'SHEET_URL', 'SCRIPT_ID', 'MODULOS_CONTRATADOS', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '39_PEDIDO_CLIENTE': Object.freeze(['ID', 'CLIENTE_ID', 'PROYECTO_ID', 'CANAL', 'FECHA_PEDIDO', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '40_PEDIDO_CLIENTE_LINEA': Object.freeze(['ID', 'PEDIDO_CLIENTE_ID', 'PRODUCTO_ID', 'CANTIDAD', 'PRECIO_UNITARIO', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '41_ENTREGA': Object.freeze(['ID', 'PEDIDO_CLIENTE_ID', 'FECHA_ENTREGA', 'RESPONSABLE_ID', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '42_ENTREGA_LINEA': Object.freeze(['ID', 'ENTREGA_ID', 'PRODUCTO_ID', 'CANTIDAD_ENTREGADA', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '43_CONTRATO_SERVICIO': Object.freeze(['ID', 'CLIENTE_ID', 'PROYECTO_ID', 'MODULOS_CONTRATADOS', 'PERIODICIDAD', 'IMPORTE_PERIODICO', 'MODALIDAD_PAGO', 'FECHA_INICIO', 'FECHA_RENOVACION', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '44_OPORTUNIDAD': Object.freeze(['ID', 'CLIENTE_ID', 'ORIGEN', 'ORIGEN_PLATAFORMA', 'ORIGEN_URL', 'AMBITO', 'DESCRIPCION_PROYECTO_ORIGEN', 'IMPORTE_OBJETIVO_CAMPANA', 'TIPO_OPORTUNIDAD', 'PUNTUACION_ENCAJE', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '45_TAREA_COMPETENCIA': Object.freeze(['ID', 'TAREA_ID', 'COMPETENCIA_ID', 'NIVEL_MINIMO', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '46_TAREA_RECURSO_NECESIDAD': Object.freeze(['ID', 'TAREA_ID', 'CLASE_RECURSO_REQUERIDA', 'CATEGORIA_RECURSO_REQUERIDA', 'CANTIDAD_MINIMA', 'CAPACIDAD_MINIMA', 'CAPACIDAD_UNIDAD', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES']),
  '90_CONFIGURACION': Object.freeze(['ID', 'CATEGORIA', 'CLAVE', 'VALOR', 'ORDEN', 'DESCRIPCION', 'ACTIVO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR']),
  '91_HISTORIAL': Object.freeze(['ID_HISTORIAL', 'TIMESTAMP', 'CORRELATION_ID', 'USUARIO', 'ACCION', 'ENTIDAD', 'REGISTRO_ID', 'ORIGEN', 'ANTES_JSON', 'DESPUES_JSON', 'RESULTADO', 'CODIGO', 'ERROR', 'ES_PRUEBA', 'PRUEBA_ID']),
  '92_ESCENARIOS': Object.freeze(['ID', 'NOMBRE', 'PERFIL', 'GUION', 'EJE_COMPETENCIA', 'EJE_RECURSO', 'EJE_AUSENCIA', 'ESTADO', 'FECHA_CREACION', 'CREADO_POR', 'FECHA_MODIFICACION', 'MODIFICADO_POR', 'ACTIVO', 'OBSERVACIONES'])
});

/**
 * Orden de creación de hojas: los 37 catálogos/entidades numerados + 90/91.
 * Debe coincidir con las claves de CABECERAS_HOJA_MVP (no se deriva de
 * Object.keys porque el orden de inserción de un objeto no está garantizado
 * como contrato público).
 */
var ORDEN_HOJAS_ESTRUCTURA_INICIAL = Object.freeze([
  '01_CAMPANAS', '02_PROYECTOS', '03_PRODUCTOS', '04_PROYECTO_PRODUCTO', '05_PROCESOS',
  '06_TAREAS', '07_TAREA_RESPONSABLE', '08_MATERIALES', '09_PRODUCTO_MATERIAL', '10_TAREA_MATERIAL',
  '11_PERSONAS_EQUIPOS', '12_DECISIONES', '13_INCIDENCIAS', '14_DOCUMENTOS', '15_PROVEEDORES',
  '16_ASIGNACION', '17_RELACION', '18_VINCULO', '19_MOVIMIENTO_MATERIAL', '20_EJECUCION_TAREA',
  '21_PROVEEDOR_MATERIAL', '22_EQUIPO_MIEMBRO', '23_RECURSO', '24_TAREA_RECURSO', '25_PEDIDO_PROVEEDOR',
  '26_PEDIDO_PROVEEDOR_LINEA', '27_RECEPCION', '28_RECEPCION_LINEA', '29_HORARIO', '30_PRESUPUESTO',
  '31_FUENTE_FINANCIACION', '32_COSTE', '33_COMPETENCIA', '34_PERSONA_COMPETENCIA', '35_RECURSO_COMPETENCIA',
  '36_CONVOCATORIA', '37_ETIQUETA_IMPACTO', '38_CLIENTE', '39_PEDIDO_CLIENTE', '40_PEDIDO_CLIENTE_LINEA',
  '41_ENTREGA', '42_ENTREGA_LINEA', '43_CONTRATO_SERVICIO', '44_OPORTUNIDAD', '45_TAREA_COMPETENCIA',
  '46_TAREA_RECURSO_NECESIDAD', '90_CONFIGURACION', '91_HISTORIAL', '92_ESCENARIOS'
]);

/**
 * Módulo dueño de cada categoría de 90_CONFIGURACION -- usado por
 * sembrarCatalogoInicial_ (EstructuraInicialService.js) para no sembrar
 * catálogo de módulos que el cliente no tiene instalados. Las categorías
 * sin entrada aquí se consideran CORE (base, siempre instalada).
 *
 * IMPORTANTE (hallazgo en vivo -- ERROR_CATALOGO: no existe el rango con
 * nombre CFG_IMPACTO al crear una Decisión/Incidencia en un cliente sin
 * el módulo IMPACTO): IMPACTO (Bajo/Medio/Alto/Crítico) NO va aquí,
 * aunque su nombre se parezca a CATEGORIA_IMPACTO -- lo usan
 * DECISION.IMPACTO e INCIDENCIA.IMPACTO, ambas entidades CORE, así que
 * tiene que sembrarse siempre. CATEGORIA_IMPACTO (Social/Ecológico/
 * Económico) sí es del módulo IMPACTO -- solo la usa ETIQUETA_IMPACTO.
 */
var MODULO_POR_CATEGORIA_CATALOGO = Object.freeze({
  CATEGORIA_MATERIAL: 'COMPRAS',
  ESTADO_MATERIAL: 'COMPRAS',
  ESTADO_PROVEEDOR: 'COMPRAS',
  ESTADO_PEDIDO_PROVEEDOR: 'COMPRAS',
  ESTADO_RECEPCION: 'COMPRAS',
  TIPO_MOVIMIENTO: 'COMPRAS',
  CATEGORIA_PRESUPUESTO: 'ECONOMICO',
  ENTIDAD_PRESUPUESTO: 'ECONOMICO',
  ESTADO_FUENTE_FINANCIACION: 'ECONOMICO',
  TIPO_FUENTE_FINANCIACION: 'ECONOMICO',
  ENTIDAD_COSTE: 'ECONOMICO',
  ESTADO_COSTE: 'ECONOMICO',
  PERIODICIDAD_COSTE: 'ECONOMICO',
  MODO_COSTE_RECURSO: 'ECONOMICO',
  ESTADO_CONVOCATORIA: 'CONVOCATORIAS',
  TIPO_CONVOCATORIA: 'CONVOCATORIAS',
  CATEGORIA_IMPACTO: 'IMPACTO',
  ESTADO_CLIENTE: 'CLIENTE',
  TIPO_CLIENTE: 'CLIENTE',
  CANAL_PEDIDO_CLIENTE: 'VENTAS',
  ESTADO_PEDIDO_CLIENTE: 'VENTAS',
  ESTADO_ENTREGA: 'VENTAS',
  PERIODICIDAD_CONTRATO: 'VENTAS',
  MODALIDAD_PAGO: 'VENTAS',
  ESTADO_CONTRATO_SERVICIO: 'VENTAS',
  ORIGEN_OPORTUNIDAD: 'OPORTUNIDAD',
  AMBITO_OPORTUNIDAD: 'OPORTUNIDAD',
  TIPO_OPORTUNIDAD: 'OPORTUNIDAD',
  ESTADO_OPORTUNIDAD: 'OPORTUNIDAD',
  SECTOR_OBJETIVO: 'OPORTUNIDAD'
});

/**
 * Semilla de 90_CONFIGURACION: transcripción literal de las 326 filas reales
 * (categoria, clave, valor, orden, descripcion). orden/descripcion son null
 * cuando la fila real de origen no los tenía rellenados (altas posteriores
 * al alta inicial del catálogo).
 */
var CATALOGO_SEMILLA_MVP = Object.freeze([
  { categoria: 'PRIORIDAD', clave: 'BAJA', valor: 'Baja', orden: 1, descripcion: 'Prioridad baja' },
  { categoria: 'PRIORIDAD', clave: 'MEDIA', valor: 'Media', orden: 2, descripcion: 'Prioridad normal' },
  { categoria: 'PRIORIDAD', clave: 'ALTA', valor: 'Alta', orden: 3, descripcion: 'Prioridad alta' },
  { categoria: 'ESTADO_CAMPANA', clave: 'BORRADOR', valor: 'Borrador', orden: 1, descripcion: 'Campaña en preparación' },
  { categoria: 'ESTADO_CAMPANA', clave: 'PLANIFICADA', valor: 'Planificada', orden: 2, descripcion: 'Campaña aprobada y pendiente de inicio' },
  { categoria: 'ESTADO_CAMPANA', clave: 'ACTIVA', valor: 'Activa', orden: 3, descripcion: 'Campaña en ejecución' },
  { categoria: 'ESTADO_CAMPANA', clave: 'PAUSADA', valor: 'Pausada', orden: 4, descripcion: 'Campaña detenida temporalmente' },
  { categoria: 'ESTADO_CAMPANA', clave: 'COMPLETADA', valor: 'Completada', orden: 5, descripcion: 'Campaña finalizada' },
  { categoria: 'ESTADO_CAMPANA', clave: 'CANCELADA', valor: 'Cancelada', orden: 6, descripcion: 'Campaña cancelada' },
  { categoria: 'ESTADO_PROYECTO', clave: 'BORRADOR', valor: 'Borrador', orden: 1, descripcion: 'Proyecto en preparación' },
  { categoria: 'ESTADO_PROYECTO', clave: 'PLANIFICADO', valor: 'Planificado', orden: 2, descripcion: 'Proyecto aprobado y pendiente de inicio' },
  { categoria: 'ESTADO_PROYECTO', clave: 'EN_PROCESO', valor: 'En proceso', orden: 3, descripcion: 'Proyecto en ejecución' },
  { categoria: 'ESTADO_PROYECTO', clave: 'BLOQUEADO', valor: 'Bloqueado', orden: 4, descripcion: 'Proyecto detenido por un bloqueo' },
  { categoria: 'ESTADO_PROYECTO', clave: 'POSPUESTO', valor: 'Pospuesto', orden: 5, descripcion: 'Proyecto aplazado' },
  { categoria: 'ESTADO_PROYECTO', clave: 'COMPLETADO', valor: 'Completado', orden: 6, descripcion: 'Proyecto finalizado' },
  { categoria: 'ESTADO_PROYECTO', clave: 'CANCELADO', valor: 'Cancelado', orden: 7, descripcion: 'Proyecto cancelado' },
  { categoria: 'TIPO_PROYECTO', clave: 'URGENTE', valor: 'Urgente', orden: 1, descripcion: 'Proyecto que requiere atención inmediata' },
  { categoria: 'TIPO_PROYECTO', clave: 'IMPORTANTE', valor: 'Importante', orden: 2, descripcion: 'Proyecto prioritario planificado' },
  { categoria: 'TIPO_PROYECTO', clave: 'PROPUESTA', valor: 'Propuesta', orden: 3, descripcion: 'Proyecto pendiente de valoración o aprobación' },
  { categoria: 'TIPO_PROYECTO', clave: 'ENCARGO_CLIENTE', valor: 'Encargo de cliente', orden: null, descripcion: null },
  { categoria: 'TIPO_PROYECTO', clave: 'PRODUCCION_PROPIA_STOCK', valor: 'Producción propia / stock', orden: null, descripcion: null },
  { categoria: 'TIPO_PROYECTO', clave: 'PROYECTO_FORMATIVO', valor: 'Proyecto formativo', orden: null, descripcion: null },
  { categoria: 'TIPO_PROYECTO', clave: 'COLABORACION_SOCIAL', valor: 'Colaboración social', orden: null, descripcion: null },
  { categoria: 'TIPO_PROYECTO', clave: 'PROTOTIPO_ID', valor: 'Prototipo / I+D', orden: null, descripcion: null },
  { categoria: 'TIPO_PROYECTO', clave: 'MANTENIMIENTO_REPARACION', valor: 'Mantenimiento / reparación', orden: null, descripcion: null },
  { categoria: 'ESTADO_PRODUCTO', clave: 'BORRADOR', valor: 'Borrador', orden: 1, descripcion: 'Producto en definición' },
  { categoria: 'ESTADO_PRODUCTO', clave: 'PLANIFICADO', valor: 'Planificado', orden: 2, descripcion: 'Producto aprobado y pendiente de producción' },
  { categoria: 'ESTADO_PRODUCTO', clave: 'EN_PRODUCCION', valor: 'En producción', orden: 3, descripcion: 'Producto en proceso de fabricación' },
  { categoria: 'ESTADO_PRODUCTO', clave: 'BLOQUEADO', valor: 'Bloqueado', orden: 4, descripcion: 'Producción detenida por un bloqueo' },
  { categoria: 'ESTADO_PRODUCTO', clave: 'COMPLETADO', valor: 'Completado', orden: 5, descripcion: 'Producción finalizada' },
  { categoria: 'ESTADO_PRODUCTO', clave: 'CANCELADO', valor: 'Cancelado', orden: 6, descripcion: 'Producto cancelado' },
  { categoria: 'ORIGEN_PRODUCTO', clave: 'PEDIDO_INTERNO', valor: 'Pedido interno', orden: 1, descripcion: 'Solicitud procedente de la organización' },
  { categoria: 'ORIGEN_PRODUCTO', clave: 'PEDIDO_EXTERNO', valor: 'Pedido externo', orden: 2, descripcion: 'Solicitud procedente de un cliente externo' },
  { categoria: 'ORIGEN_PRODUCTO', clave: 'PRODUCCION_PROPIA', valor: 'Producción propia', orden: 3, descripcion: 'Producción iniciada por el taller' },
  { categoria: 'ESTADO_PROCESO', clave: 'PENDIENTE', valor: 'Pendiente', orden: 1, descripcion: 'Proceso pendiente de inicio' },
  { categoria: 'ESTADO_PROCESO', clave: 'PREPARADO', valor: 'Preparado', orden: 2, descripcion: 'Proceso listo para comenzar' },
  { categoria: 'ESTADO_PROCESO', clave: 'EN_PROCESO', valor: 'En proceso', orden: 3, descripcion: 'Proceso en ejecución' },
  { categoria: 'ESTADO_PROCESO', clave: 'BLOQUEADO', valor: 'Bloqueado', orden: 4, descripcion: 'Proceso detenido por un bloqueo' },
  { categoria: 'ESTADO_PROCESO', clave: 'COMPLETADO', valor: 'Completado', orden: 5, descripcion: 'Proceso finalizado' },
  { categoria: 'ESTADO_PROCESO', clave: 'CANCELADO', valor: 'Cancelado', orden: 6, descripcion: 'Proceso cancelado' },
  { categoria: 'ESTADO_TAREA', clave: 'PENDIENTE', valor: 'Pendiente', orden: 1, descripcion: 'Tarea pendiente de preparación' },
  { categoria: 'ESTADO_TAREA', clave: 'PREPARADA', valor: 'Preparada', orden: 2, descripcion: 'Tarea lista para comenzar' },
  { categoria: 'ESTADO_TAREA', clave: 'EN_PROCESO', valor: 'En proceso', orden: 3, descripcion: 'Tarea en ejecución' },
  { categoria: 'ESTADO_TAREA', clave: 'BLOQUEADA', valor: 'Bloqueada', orden: 4, descripcion: 'Tarea detenida por un bloqueo' },
  { categoria: 'ESTADO_TAREA', clave: 'POSPUESTA', valor: 'Pospuesta', orden: 5, descripcion: 'Tarea aplazada' },
  { categoria: 'ESTADO_TAREA', clave: 'TERMINADA', valor: 'Terminada', orden: 6, descripcion: 'Tarea finalizada' },
  { categoria: 'ESTADO_TAREA', clave: 'CANCELADA', valor: 'Cancelada', orden: 7, descripcion: 'Tarea cancelada' },
  { categoria: 'UNIDAD', clave: 'UNIDAD', valor: 'Unidad', orden: 1, descripcion: 'Conteo por unidades' },
  { categoria: 'UNIDAD', clave: 'KG', valor: 'Kilogramo', orden: 2, descripcion: 'Peso en kilogramos' },
  { categoria: 'UNIDAD', clave: 'G', valor: 'Gramo', orden: 3, descripcion: 'Peso en gramos' },
  { categoria: 'UNIDAD', clave: 'L', valor: 'Litro', orden: 4, descripcion: 'Volumen en litros' },
  { categoria: 'UNIDAD', clave: 'ML', valor: 'Mililitro', orden: 5, descripcion: 'Volumen en mililitros' },
  { categoria: 'UNIDAD', clave: 'M', valor: 'Metro', orden: 6, descripcion: 'Longitud en metros' },
  { categoria: 'UNIDAD', clave: 'M2', valor: 'Metro cuadrado', orden: 7, descripcion: 'Superficie en metros cuadrados' },
  { categoria: 'UNIDAD', clave: 'HORA', valor: 'Hora', orden: 8, descripcion: 'Tiempo en horas' },
  { categoria: 'ESTADO_DECISION', clave: 'PENDIENTE_INFORMACION', valor: 'Pendiente de información', orden: 1, descripcion: 'Faltan datos para decidir' },
  { categoria: 'ESTADO_DECISION', clave: 'PENDIENTE_CONSENSO', valor: 'Pendiente de consenso', orden: 2, descripcion: 'Requiere acuerdo entre responsables' },
  { categoria: 'ESTADO_DECISION', clave: 'PENDIENTE_APROBACION', valor: 'Pendiente de aprobación', orden: 3, descripcion: 'Requiere aprobación formal' },
  { categoria: 'ESTADO_DECISION', clave: 'APROBADA', valor: 'Aprobada', orden: 4, descripcion: 'Decisión aprobada' },
  { categoria: 'ESTADO_DECISION', clave: 'RECHAZADA', valor: 'Rechazada', orden: 5, descripcion: 'Decisión rechazada' },
  { categoria: 'ESTADO_DECISION', clave: 'SUSTITUIDA', valor: 'Sustituida', orden: 6, descripcion: 'Reemplazada por otra decisión' },
  { categoria: 'ESTADO_INCIDENCIA', clave: 'ABIERTA', valor: 'Abierta', orden: 1, descripcion: 'Incidencia registrada y pendiente de tratamiento' },
  { categoria: 'ESTADO_INCIDENCIA', clave: 'EN_ANALISIS', valor: 'En análisis', orden: 2, descripcion: 'Incidencia en evaluación' },
  { categoria: 'ESTADO_INCIDENCIA', clave: 'EN_RESOLUCION', valor: 'En resolución', orden: 3, descripcion: 'Acción correctora en ejecución' },
  { categoria: 'ESTADO_INCIDENCIA', clave: 'BLOQUEADA', valor: 'Bloqueada', orden: 4, descripcion: 'Resolución detenida por una dependencia' },
  { categoria: 'ESTADO_INCIDENCIA', clave: 'RESUELTA', valor: 'Resuelta', orden: 5, descripcion: 'Incidencia solucionada' },
  { categoria: 'ESTADO_INCIDENCIA', clave: 'CERRADA', valor: 'Cerrada', orden: 6, descripcion: 'Resolución verificada y cerrada' },
  { categoria: 'ESTADO_INCIDENCIA', clave: 'CANCELADA', valor: 'Cancelada', orden: 7, descripcion: 'Incidencia anulada' },
  { categoria: 'TIPO_INCIDENCIA', clave: 'CALIDAD', valor: 'Calidad', orden: 1, descripcion: 'Defecto, rechazo o resultado no conforme' },
  { categoria: 'TIPO_INCIDENCIA', clave: 'MATERIAL', valor: 'Material', orden: 2, descripcion: 'Falta, defecto o problema de material' },
  { categoria: 'TIPO_INCIDENCIA', clave: 'MAQUINARIA', valor: 'Maquinaria', orden: 3, descripcion: 'Avería o indisponibilidad de maquinaria' },
  { categoria: 'TIPO_INCIDENCIA', clave: 'PLANIFICACION', valor: 'Planificación', orden: 4, descripcion: 'Desviación de fechas, carga o secuencia' },
  { categoria: 'TIPO_INCIDENCIA', clave: 'SEGURIDAD', valor: 'Seguridad', orden: 5, descripcion: 'Riesgo o incumplimiento preventivo' },
  { categoria: 'TIPO_INCIDENCIA', clave: 'DOCUMENTACION', valor: 'Documentación', orden: 6, descripcion: 'Falta o error en instrucciones, diseño o protocolo' },
  { categoria: 'TIPO_INCIDENCIA', clave: 'FUNCIONAL', valor: 'Funcional', orden: null, descripcion: null },
  { categoria: 'TIPO_INCIDENCIA', clave: 'USABILIDAD', valor: 'Usabilidad', orden: null, descripcion: null },
  { categoria: 'TIPO_INCIDENCIA', clave: 'DATOS', valor: 'Datos', orden: null, descripcion: null },
  { categoria: 'TIPO_INCIDENCIA', clave: 'INTEGRACION', valor: 'Integración', orden: null, descripcion: null },
  { categoria: 'TIPO_INCIDENCIA', clave: 'RENDIMIENTO', valor: 'Rendimiento', orden: null, descripcion: null },
  { categoria: 'TIPO_INCIDENCIA', clave: 'TRAZABILIDAD', valor: 'Trazabilidad', orden: null, descripcion: null },
  { categoria: 'TIPO_INCIDENCIA', clave: 'AUTOMATIZACION', valor: 'Automatización', orden: null, descripcion: null },
  { categoria: 'TIPO_INCIDENCIA', clave: 'OTRA', valor: 'Otra', orden: 7, descripcion: 'Incidencia no incluida en las categorías anteriores' },
  { categoria: 'CATEGORIA_MATERIAL', clave: 'MADERA', valor: 'Madera', orden: 1, descripcion: 'Maderas, tableros y derivados' },
  { categoria: 'CATEGORIA_MATERIAL', clave: 'FERRETERIA', valor: 'Ferretería', orden: 2, descripcion: 'Tornillería, herrajes y elementos de unión' },
  { categoria: 'CATEGORIA_MATERIAL', clave: 'PINTURA', valor: 'Pintura y acabado', orden: 3, descripcion: 'Pinturas, barnices y productos de acabado' },
  { categoria: 'CATEGORIA_MATERIAL', clave: 'ADHESIVO', valor: 'Adhesivo', orden: 4, descripcion: 'Colas, adhesivos y selladores' },
  { categoria: 'CATEGORIA_MATERIAL', clave: 'CONSUMIBLE', valor: 'Consumible', orden: 5, descripcion: 'Material auxiliar de consumo' },
  { categoria: 'CATEGORIA_MATERIAL', clave: 'EMBALAJE', valor: 'Embalaje', orden: 6, descripcion: 'Material para protección y entrega' },
  { categoria: 'CATEGORIA_MATERIAL', clave: 'OTRO', valor: 'Otro', orden: 7, descripcion: 'Material no clasificado' },
  { categoria: 'ESTADO_MATERIAL', clave: 'DISPONIBLE', valor: 'Disponible', orden: 1, descripcion: 'Material disponible para su uso' },
  { categoria: 'ESTADO_MATERIAL', clave: 'STOCK_BAJO', valor: 'Stock bajo', orden: 2, descripcion: 'Existencias iguales o inferiores al mínimo' },
  { categoria: 'ESTADO_MATERIAL', clave: 'AGOTADO', valor: 'Agotado', orden: 3, descripcion: 'Material sin existencias disponibles' },
  { categoria: 'ESTADO_MATERIAL', clave: 'RESERVADO', valor: 'Reservado', orden: 4, descripcion: 'Material reservado para producción' },
  { categoria: 'ESTADO_MATERIAL', clave: 'NO_UTILIZABLE', valor: 'No utilizable', orden: 5, descripcion: 'Material defectuoso, caducado o bloqueado' },
  { categoria: 'ESTADO_MATERIAL', clave: 'DESCATALOGADO', valor: 'Descatalogado', orden: 6, descripcion: 'Material que ya no debe utilizarse' },
  { categoria: 'TIPO_RECURSO', clave: 'PERSONA', valor: 'Persona', orden: 1, descripcion: 'Recurso humano individual' },
  { categoria: 'TIPO_RECURSO', clave: 'EQUIPO', valor: 'Equipo', orden: 2, descripcion: 'Grupo de personas o unidad de trabajo' },
  { categoria: 'ESTADO_RECURSO', clave: 'DISPONIBLE', valor: 'Disponible', orden: 1, descripcion: 'Recurso disponible para asignaciones' },
  { categoria: 'ESTADO_RECURSO', clave: 'DISPONIBILIDAD_PARCIAL', valor: 'Disponibilidad parcial', orden: 2, descripcion: 'Recurso disponible con limitaciones' },
  { categoria: 'ESTADO_RECURSO', clave: 'NO_DISPONIBLE', valor: 'No disponible', orden: 3, descripcion: 'Recurso temporalmente no disponible' },
  { categoria: 'ESTADO_RECURSO', clave: 'INACTIVO', valor: 'Inactivo', orden: 4, descripcion: 'Recurso fuera de uso o de la organización' },
  { categoria: 'TIPO_DOCUMENTO', clave: 'DISEÑO', valor: 'Diseño', orden: 1, descripcion: 'Planos, bocetos o especificaciones del producto' },
  { categoria: 'TIPO_DOCUMENTO', clave: 'MANUAL', valor: 'Manual', orden: 2, descripcion: 'Instrucciones de uso o fabricación' },
  { categoria: 'TIPO_DOCUMENTO', clave: 'PROTOCOLO', valor: 'Protocolo', orden: 3, descripcion: 'Procedimiento operativo o preventivo' },
  { categoria: 'TIPO_DOCUMENTO', clave: 'FICHA_TECNICA', valor: 'Ficha técnica', orden: 4, descripcion: 'Características técnicas del producto o material' },
  { categoria: 'TIPO_DOCUMENTO', clave: 'PRESUPUESTO', valor: 'Presupuesto', orden: 5, descripcion: 'Estimación económica asociada' },
  { categoria: 'TIPO_DOCUMENTO', clave: 'INFORME', valor: 'Informe', orden: 6, descripcion: 'Documento de seguimiento, análisis o resultados' },
  { categoria: 'TIPO_DOCUMENTO', clave: 'ACTA', valor: 'Acta', orden: 7, descripcion: 'Registro formal de acuerdos o reuniones' },
  { categoria: 'TIPO_DOCUMENTO', clave: 'PLAN', valor: 'Plan', orden: null, descripcion: null },
  { categoria: 'TIPO_DOCUMENTO', clave: 'ESPECIFICACION', valor: 'Especificación', orden: null, descripcion: null },
  { categoria: 'TIPO_DOCUMENTO', clave: 'REQUISITOS', valor: 'Requisitos', orden: null, descripcion: null },
  { categoria: 'TIPO_DOCUMENTO', clave: 'TUTORIAL', valor: 'Tutorial', orden: null, descripcion: null },
  { categoria: 'TIPO_DOCUMENTO', clave: 'CHECKLIST', valor: 'Checklist', orden: null, descripcion: null },
  { categoria: 'TIPO_DOCUMENTO', clave: 'MEMORIA', valor: 'Memoria', orden: null, descripcion: null },
  { categoria: 'TIPO_DOCUMENTO', clave: 'EVIDENCIA', valor: 'Evidencia', orden: null, descripcion: null },
  { categoria: 'TIPO_DOCUMENTO', clave: 'PRUEBA', valor: 'Prueba', orden: null, descripcion: null },
  { categoria: 'TIPO_DOCUMENTO', clave: 'REFERENCIA', valor: 'Referencia', orden: null, descripcion: null },
  { categoria: 'TIPO_DOCUMENTO', clave: 'DECISION', valor: 'Decisión', orden: null, descripcion: null },
  { categoria: 'TIPO_DOCUMENTO', clave: 'OTRO', valor: 'Otro', orden: 8, descripcion: 'Documento no incluido en las categorías anteriores' },
  { categoria: 'ESTADO_DOCUMENTO', clave: 'BORRADOR', valor: 'Borrador', orden: 1, descripcion: 'Documento en elaboración' },
  { categoria: 'ESTADO_DOCUMENTO', clave: 'PENDIENTE_REVISION', valor: 'Pendiente de revisión', orden: 2, descripcion: 'Documento pendiente de validación' },
  { categoria: 'ESTADO_DOCUMENTO', clave: 'VIGENTE', valor: 'Vigente', orden: 3, descripcion: 'Documento aprobado y aplicable' },
  { categoria: 'ESTADO_DOCUMENTO', clave: 'OBSOLETO', valor: 'Obsoleto', orden: 4, descripcion: 'Documento sustituido o fuera de uso' },
  { categoria: 'ESTADO_DOCUMENTO', clave: 'ARCHIVADO', valor: 'Archivado', orden: 5, descripcion: 'Documento conservado como histórico' },
  { categoria: 'ESTADO_DOCUMENTO', clave: 'CANCELADO', valor: 'Cancelado', orden: 6, descripcion: 'Documento anulado antes de su aprobación' },
  { categoria: 'ENTIDAD_DOCUMENTO', clave: 'CAMPANA', valor: 'Campaña', orden: 1, descripcion: 'Documento relacionado con una campaña' },
  { categoria: 'ENTIDAD_DOCUMENTO', clave: 'PROYECTO', valor: 'Proyecto', orden: 2, descripcion: 'Documento relacionado con un proyecto' },
  { categoria: 'ENTIDAD_DOCUMENTO', clave: 'PRODUCTO', valor: 'Producto', orden: 3, descripcion: 'Documento relacionado con un producto' },
  { categoria: 'ENTIDAD_DOCUMENTO', clave: 'PROCESO', valor: 'Proceso', orden: 4, descripcion: 'Documento relacionado con un proceso' },
  { categoria: 'ENTIDAD_DOCUMENTO', clave: 'TAREA', valor: 'Tarea', orden: 5, descripcion: 'Documento relacionado con una tarea' },
  { categoria: 'ENTIDAD_DOCUMENTO', clave: 'DECISION', valor: 'Decisión', orden: 6, descripcion: 'Documento relacionado con una decisión' },
  { categoria: 'ENTIDAD_DOCUMENTO', clave: 'INCIDENCIA', valor: 'Incidencia', orden: 7, descripcion: 'Documento relacionado con una incidencia' },
  { categoria: 'ENTIDAD_DOCUMENTO', clave: 'DOCUMENTO', valor: 'Documento', orden: null, descripcion: null },
  { categoria: 'ENTIDAD_DOCUMENTO', clave: 'RECURSO', valor: 'Recurso', orden: null, descripcion: null },
  { categoria: 'ENTIDAD_DOCUMENTO', clave: 'PERSONA_EQUIPO', valor: 'Persona/Equipo', orden: null, descripcion: null },
  { categoria: 'ENTIDAD_DOCUMENTO', clave: 'CONVOCATORIA', valor: 'Convocatoria', orden: null, descripcion: null },
  { categoria: 'ENTIDAD_DOCUMENTO', clave: 'CLIENTE', valor: 'Cliente', orden: null, descripcion: null },
  { categoria: 'ESTADO_ASIGNACION', clave: 'PLANIFICADA', valor: 'Planificada', orden: 1, descripcion: 'Asignación prevista y pendiente de inicio' },
  { categoria: 'ESTADO_ASIGNACION', clave: 'ACTIVA', valor: 'Activa', orden: 2, descripcion: 'Asignación actualmente vigente' },
  { categoria: 'ESTADO_ASIGNACION', clave: 'COMPLETADA', valor: 'Completada', orden: 3, descripcion: 'Asignación finalizada' },
  { categoria: 'ESTADO_ASIGNACION', clave: 'CANCELADA', valor: 'Cancelada', orden: 4, descripcion: 'Asignación anulada' },
  { categoria: 'ESTADO_RELACION', clave: 'PLANIFICADA', valor: 'Planificada', orden: 1, descripcion: 'Relación prevista y pendiente de activación' },
  { categoria: 'ESTADO_RELACION', clave: 'ACTIVA', valor: 'Activa', orden: 2, descripcion: 'Relación actualmente vigente' },
  { categoria: 'ESTADO_RELACION', clave: 'COMPLETADA', valor: 'Completada', orden: 3, descripcion: 'Relación finalizada correctamente' },
  { categoria: 'ESTADO_RELACION', clave: 'CANCELADA', valor: 'Cancelada', orden: 4, descripcion: 'Relación anulada' },
  { categoria: 'TIPO_DECISION', clave: 'TECNICA', valor: 'Técnica', orden: 1, descripcion: 'Decisión sobre diseño, materiales o método de trabajo' },
  { categoria: 'TIPO_DECISION', clave: 'PLANIFICACION', valor: 'Planificación', orden: 2, descripcion: 'Decisión sobre fechas, prioridades o secuencias' },
  { categoria: 'TIPO_DECISION', clave: 'RECURSOS', valor: 'Recursos', orden: 3, descripcion: 'Decisión sobre personas, equipos o capacidad' },
  { categoria: 'TIPO_DECISION', clave: 'PRODUCCION', valor: 'Producción', orden: 4, descripcion: 'Decisión sobre ejecución o fabricación' },
  { categoria: 'TIPO_DECISION', clave: 'CALIDAD', valor: 'Calidad', orden: 5, descripcion: 'Decisión sobre criterios o resultados de calidad' },
  { categoria: 'TIPO_DECISION', clave: 'ORGANIZATIVA', valor: 'Organizativa', orden: 6, descripcion: 'Decisión sobre coordinación o funcionamiento' },
  { categoria: 'TIPO_DECISION', clave: 'OTRA', valor: 'Otra', orden: 7, descripcion: 'Decisión no incluida en las categorías anteriores' },
  { categoria: 'IMPACTO', clave: 'BAJO', valor: 'Bajo', orden: 1, descripcion: 'Impacto limitado y asumible sin replanificación relevante' },
  { categoria: 'IMPACTO', clave: 'MEDIO', valor: 'Medio', orden: 2, descripcion: 'Impacto que requiere seguimiento o ajustes parciales' },
  { categoria: 'IMPACTO', clave: 'ALTO', valor: 'Alto', orden: 3, descripcion: 'Impacto relevante sobre plazos, recursos o producción' },
  { categoria: 'IMPACTO', clave: 'CRITICO', valor: 'Crítico', orden: 4, descripcion: 'Impacto grave que exige actuación o decisión inmediata' },
  { categoria: 'ROL_ASIGNACION', clave: 'RESPONSABLE', valor: 'Responsable', orden: 1, descripcion: 'Responsable principal de la ejecución de la tarea' },
  { categoria: 'ROL_ASIGNACION', clave: 'COLABORADOR', valor: 'Colaborador', orden: 2, descripcion: 'Participa en la ejecución de la tarea' },
  { categoria: 'ROL_ASIGNACION', clave: 'SUPERVISOR', valor: 'Supervisor', orden: 3, descripcion: 'Supervisa o valida la ejecución de la tarea' },
  { categoria: 'ROL_ASIGNACION', clave: 'APOYO', valor: 'Apoyo', orden: 4, descripcion: 'Presta apoyo puntual o especializado' },
  { categoria: 'ROL_ASIGNACION', clave: 'EJECUTOR', valor: 'Ejecutor', orden: null, descripcion: null },
  { categoria: 'ROL_ASIGNACION', clave: 'CONSULTADO', valor: 'Consultado', orden: null, descripcion: null },
  { categoria: 'ROL_ASIGNACION', clave: 'INFORMADO', valor: 'Informado', orden: null, descripcion: null },
  { categoria: 'ROL_ASIGNACION', clave: 'COORDINADOR', valor: 'Coordinador', orden: null, descripcion: null },
  { categoria: 'ROL_ASIGNACION', clave: 'VALIDADOR', valor: 'Validador', orden: null, descripcion: null },
  { categoria: 'DISPONIBILIDAD', clave: 'COMPLETA', valor: 'Completa', orden: 1, descripcion: 'Recurso disponible según su capacidad semanal' },
  { categoria: 'DISPONIBILIDAD', clave: 'PARCIAL', valor: 'Parcial', orden: 2, descripcion: 'Recurso disponible con limitaciones de tiempo' },
  { categoria: 'DISPONIBILIDAD', clave: 'PUNTUAL', valor: 'Puntual', orden: 3, descripcion: 'Recurso disponible únicamente para apoyos concretos' },
  { categoria: 'DISPONIBILIDAD', clave: 'NO_DISPONIBLE', valor: 'No disponible', orden: 4, descripcion: 'Recurso sin disponibilidad para nuevas asignaciones' },
  { categoria: 'ESTADO_PROVEEDOR', clave: 'ACTIVO', valor: 'Activo', orden: 1, descripcion: 'Proveedor operativo y disponible para nuevos pedidos' },
  { categoria: 'ESTADO_PROVEEDOR', clave: 'INACTIVO', valor: 'Inactivo', orden: 2, descripcion: 'Proveedor sin relación comercial activa' },
  { categoria: 'ESTADO_PROVEEDOR', clave: 'BLOQUEADO', valor: 'Bloqueado', orden: 3, descripcion: 'Proveedor bloqueado por incidencias o incumplimiento' },
  { categoria: 'NIVEL_INCIDENCIA', clave: 'GENERAL', valor: 'General', orden: 1, descripcion: 'Incidencia general sin relación jerárquica obligatoria.' },
  { categoria: 'NIVEL_INCIDENCIA', clave: 'CAMPANA', valor: 'Campaña', orden: 2, descripcion: 'Incidencia relacionada con una campaña.' },
  { categoria: 'NIVEL_INCIDENCIA', clave: 'PROYECTO', valor: 'Proyecto', orden: 3, descripcion: 'Incidencia relacionada con un proyecto.' },
  { categoria: 'NIVEL_INCIDENCIA', clave: 'PRODUCTO', valor: 'Producto', orden: 4, descripcion: 'Incidencia relacionada con un producto.' },
  { categoria: 'NIVEL_INCIDENCIA', clave: 'PROCESO', valor: 'Proceso', orden: 5, descripcion: 'Incidencia relacionada con un proceso.' },
  { categoria: 'NIVEL_INCIDENCIA', clave: 'TAREA', valor: 'Tarea', orden: 6, descripcion: 'Incidencia relacionada con una tarea.' },
  { categoria: 'NIVEL_INCIDENCIA', clave: 'CLIENTE', valor: 'Cliente', orden: 7, descripcion: 'Incidencia de mantenimiento/soporte sobre un cliente, sin proyecto activo asociado.' },
  { categoria: 'TIPO_CLIENTE', clave: 'ENTIDAD_SOCIAL', valor: 'Entidad social', orden: 1, descripcion: null },
  { categoria: 'TIPO_CLIENTE', clave: 'AYUNTAMIENTO', valor: 'Ayuntamiento', orden: 2, descripcion: null },
  { categoria: 'TIPO_CLIENTE', clave: 'EMPRESA', valor: 'Empresa', orden: 3, descripcion: null },
  { categoria: 'TIPO_CLIENTE', clave: 'PARTICULAR', valor: 'Particular', orden: 4, descripcion: null },
  { categoria: 'TIPO_CLIENTE', clave: 'CLIENTE_SOFTWARE', valor: 'Cliente de software', orden: 5, descripcion: 'Cliente Nivel 1 del propio Gestor de Proyectos (montaje de Sheet/Apps Script).' },
  { categoria: 'ESTADO_CLIENTE', clave: 'PROSPECTO', valor: 'Prospecto', orden: 1, descripcion: 'Cliente potencial, sin relación comercial confirmada todavía.' },
  { categoria: 'ESTADO_CLIENTE', clave: 'ACTIVO', valor: 'Activo', orden: 2, descripcion: 'Cliente con relación comercial activa.' },
  { categoria: 'ESTADO_CLIENTE', clave: 'EN_PAUSA', valor: 'En pausa', orden: 3, descripcion: 'Relación comercial suspendida temporalmente.' },
  { categoria: 'ESTADO_CLIENTE', clave: 'BAJA', valor: 'Baja', orden: 4, descripcion: 'Cliente sin relación comercial vigente.' },
  { categoria: 'TIPO_RELACION', clave: 'DEPENDE_DE', valor: 'Depende de', orden: null, descripcion: null },
  { categoria: 'TIPO_RELACION', clave: 'BLOQUEA', valor: 'Bloquea', orden: null, descripcion: null },
  { categoria: 'TIPO_RELACION', clave: 'REQUIERE', valor: 'Requiere', orden: null, descripcion: null },
  { categoria: 'TIPO_RELACION', clave: 'DUPLICA', valor: 'Duplica', orden: null, descripcion: null },
  { categoria: 'TIPO_RELACION', clave: 'COMPLEMENTA', valor: 'Complementa', orden: null, descripcion: null },
  { categoria: 'TIPO_RELACION', clave: 'SUSTITUYE', valor: 'Sustituye', orden: null, descripcion: null },
  { categoria: 'TIPO_RELACION', clave: 'COMPARTE_RECURSOS', valor: 'Comparte recursos', orden: null, descripcion: null },
  { categoria: 'TIPO_RELACION', clave: 'FIN_A_INICIO', valor: 'Fin a inicio', orden: null, descripcion: null },
  { categoria: 'TIPO_RELACION', clave: 'INICIO_A_INICIO', valor: 'Inicio a inicio', orden: null, descripcion: null },
  { categoria: 'TIPO_RELACION', clave: 'FIN_A_FIN', valor: 'Fin a fin', orden: null, descripcion: null },
  { categoria: 'TIPO_VINCULO', clave: 'CONTEXTO', valor: 'Contexto', orden: null, descripcion: null },
  { categoria: 'TIPO_VINCULO', clave: 'EVIDENCIA', valor: 'Evidencia', orden: null, descripcion: null },
  { categoria: 'TIPO_VINCULO', clave: 'RESULTADO', valor: 'Resultado', orden: null, descripcion: null },
  { categoria: 'TIPO_VINCULO', clave: 'MANUAL', valor: 'Manual', orden: null, descripcion: null },
  { categoria: 'TIPO_VINCULO', clave: 'TUTORIAL', valor: 'Tutorial', orden: null, descripcion: null },
  { categoria: 'TIPO_VINCULO', clave: 'ACTA', valor: 'Acta', orden: null, descripcion: null },
  { categoria: 'TIPO_VINCULO', clave: 'REFERENCIA', valor: 'Referencia', orden: null, descripcion: null },
  { categoria: 'TIPO_VINCULO', clave: 'APROBACION', valor: 'Aprobación', orden: null, descripcion: null },
  { categoria: 'TIPO_VINCULO', clave: 'BLOQUEA', valor: 'Bloquea', orden: null, descripcion: null },
  { categoria: 'TIPO_VINCULO', clave: 'RELACIONADA', valor: 'Relacionada', orden: null, descripcion: null },
  { categoria: 'TIPO_VINCULO', clave: 'DETECTADA_EN', valor: 'Detectada en', orden: null, descripcion: null },
  { categoria: 'TIPO_VINCULO', clave: 'CAUSADA_POR', valor: 'Causada por', orden: null, descripcion: null },
  { categoria: 'TIPO_VINCULO', clave: 'CORRIGE', valor: 'Corrige', orden: null, descripcion: null },
  { categoria: 'TIPO_VINCULO', clave: 'VERIFICA', valor: 'Verifica', orden: null, descripcion: null },
  { categoria: 'TIPO_VINCULO', clave: 'PREVIENE', valor: 'Previene', orden: null, descripcion: null },
  { categoria: 'MODO_USO', clave: 'REFERENCIA_COMPARTIDA', valor: 'Referencia compartida (se usa tal cual, sin copiarlo)', orden: null, descripcion: null },
  { categoria: 'MODO_USO', clave: 'REUTILIZACION_SIN_CAMBIOS', valor: 'Reutilización sin cambios (mismo diseño, otro proyecto)', orden: null, descripcion: null },
  { categoria: 'MODO_USO', clave: 'ADAPTACION_ESPECIFICA', valor: 'Adaptación específica (variante modificada para este proyecto)', orden: null, descripcion: null },
  { categoria: 'MODO_USO', clave: 'CLONACION_COMO_NUEVO', valor: 'Clonación como nuevo (copia independiente para modificar)', orden: null, descripcion: null },
  { categoria: 'TIPO_MOVIMIENTO', clave: 'ENTRADA', valor: 'Entrada', orden: null, descripcion: null },
  { categoria: 'TIPO_MOVIMIENTO', clave: 'RESERVA', valor: 'Reserva', orden: null, descripcion: null },
  { categoria: 'TIPO_MOVIMIENTO', clave: 'LIBERACION_RESERVA', valor: 'Liberación de reserva', orden: null, descripcion: null },
  { categoria: 'TIPO_MOVIMIENTO', clave: 'SALIDA', valor: 'Salida', orden: null, descripcion: null },
  { categoria: 'TIPO_MOVIMIENTO', clave: 'CONSUMO', valor: 'Consumo', orden: null, descripcion: null },
  { categoria: 'TIPO_MOVIMIENTO', clave: 'MERMA', valor: 'Merma', orden: null, descripcion: null },
  { categoria: 'TIPO_MOVIMIENTO', clave: 'DEVOLUCION', valor: 'Devolución', orden: null, descripcion: null },
  { categoria: 'TIPO_MOVIMIENTO', clave: 'TRASLADO', valor: 'Traslado', orden: null, descripcion: null },
  { categoria: 'TIPO_MOVIMIENTO', clave: 'AJUSTE_POSITIVO', valor: 'Ajuste positivo', orden: null, descripcion: null },
  { categoria: 'TIPO_MOVIMIENTO', clave: 'AJUSTE_NEGATIVO', valor: 'Ajuste negativo', orden: null, descripcion: null },
  { categoria: 'RESULTADO_EJECUCION', clave: 'EXITOSA', valor: 'Exitosa', orden: null, descripcion: null },
  { categoria: 'RESULTADO_EJECUCION', clave: 'CON_INCIDENCIAS', valor: 'Con incidencias', orden: null, descripcion: null },
  { categoria: 'RESULTADO_EJECUCION', clave: 'FALLIDA', valor: 'Fallida', orden: null, descripcion: null },
  { categoria: 'METODO_CALCULO_AVANCE', clave: 'MANUAL', valor: 'Manual', orden: null, descripcion: null },
  { categoria: 'METODO_CALCULO_AVANCE', clave: 'POR_TAREAS', valor: 'Por tareas', orden: null, descripcion: null },
  { categoria: 'METODO_CALCULO_AVANCE', clave: 'POR_ESTADO', valor: 'Por estado', orden: null, descripcion: null },
  { categoria: 'ROL_PERSONA', clave: 'COORDINACION', valor: 'Coordinación', orden: null, descripcion: null },
  { categoria: 'ROL_PERSONA', clave: 'PRODUCCION', valor: 'Producción', orden: null, descripcion: null },
  { categoria: 'ROL_PERSONA', clave: 'DISENO', valor: 'Diseño', orden: null, descripcion: null },
  { categoria: 'ROL_PERSONA', clave: 'LOGISTICA', valor: 'Logística', orden: null, descripcion: null },
  { categoria: 'ROL_PERSONA', clave: 'ADMINISTRACION', valor: 'Administración', orden: null, descripcion: null },
  { categoria: 'ROL_PERSONA', clave: 'VOLUNTARIADO', valor: 'Voluntariado', orden: null, descripcion: null },
  { categoria: 'ROL_PERSONA', clave: 'PERSONA_ATENDIDA', valor: 'Persona atendida', orden: null, descripcion: null },
  { categoria: 'ROL_PERSONA', clave: 'OTRA', valor: 'Otra', orden: null, descripcion: null },
  { categoria: 'CLASE_RECURSO', clave: 'HERRAMIENTA', valor: 'Herramienta', orden: null, descripcion: null },
  { categoria: 'CLASE_RECURSO', clave: 'MAQUINARIA', valor: 'Maquinaria', orden: null, descripcion: null },
  { categoria: 'CLASE_RECURSO', clave: 'EQUIPO_AUXILIAR', valor: 'Equipo auxiliar', orden: null, descripcion: null },
  { categoria: 'CLASE_RECURSO', clave: 'ESPACIO', valor: 'Espacio', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_RECURSO', clave: 'HERRAMIENTA_MANUAL', valor: 'Herramienta manual', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_RECURSO', clave: 'HERRAMIENTA_ELECTRICA', valor: 'Herramienta eléctrica', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_RECURSO', clave: 'UTIL_PLANTILLA', valor: 'Útil o plantilla', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_RECURSO', clave: 'MAQUINARIA_FIJA', valor: 'Maquinaria fija', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_RECURSO', clave: 'EQUIPO_INFORMATICO', valor: 'Equipo informático', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_RECURSO', clave: 'EQUIPO_PROTECCION', valor: 'Equipo de protección', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_RECURSO', clave: 'ESPACIO_PRODUCTIVO', valor: 'Espacio productivo', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_RECURSO', clave: 'ESPACIO_ALMACENAMIENTO', valor: 'Espacio de almacenamiento', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_RECURSO', clave: 'ESPACIO_FORMATIVO', valor: 'Espacio formativo', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_RECURSO', clave: 'ESPACIO_POLIVALENTE', valor: 'Espacio polivalente', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_RECURSO', clave: 'OTRO', valor: 'Otro', orden: null, descripcion: null },
  { categoria: 'ESTADO_RECURSO_FISICO', clave: 'DISPONIBLE', valor: 'Disponible', orden: null, descripcion: null },
  { categoria: 'ESTADO_RECURSO_FISICO', clave: 'EN_USO', valor: 'En uso', orden: null, descripcion: null },
  { categoria: 'ESTADO_RECURSO_FISICO', clave: 'EN_MANTENIMIENTO', valor: 'En mantenimiento', orden: null, descripcion: null },
  { categoria: 'ESTADO_RECURSO_FISICO', clave: 'AVERIADO', valor: 'Averiado', orden: null, descripcion: null },
  { categoria: 'ESTADO_RECURSO_FISICO', clave: 'DE_BAJA', valor: 'De baja', orden: null, descripcion: null },
  { categoria: 'TIPO_USO_RECURSO', clave: 'UTILIZA', valor: 'Utiliza', orden: null, descripcion: null },
  { categoria: 'TIPO_USO_RECURSO', clave: 'RESERVA', valor: 'Reserva', orden: null, descripcion: null },
  { categoria: 'TIPO_USO_RECURSO', clave: 'OCUPA', valor: 'Ocupa', orden: null, descripcion: null },
  { categoria: 'TIPO_USO_RECURSO', clave: 'REQUIERE', valor: 'Requiere', orden: null, descripcion: null },
  { categoria: 'ESTADO_PEDIDO_PROVEEDOR', clave: 'BORRADOR', valor: 'Borrador', orden: null, descripcion: null },
  { categoria: 'ESTADO_PEDIDO_PROVEEDOR', clave: 'ENVIADO', valor: 'Enviado', orden: null, descripcion: null },
  { categoria: 'ESTADO_PEDIDO_PROVEEDOR', clave: 'CONFIRMADO', valor: 'Confirmado', orden: null, descripcion: null },
  { categoria: 'ESTADO_PEDIDO_PROVEEDOR', clave: 'RECIBIDO_PARCIAL', valor: 'Recibido parcial', orden: null, descripcion: null },
  { categoria: 'ESTADO_PEDIDO_PROVEEDOR', clave: 'RECIBIDO_COMPLETO', valor: 'Recibido completo', orden: null, descripcion: null },
  { categoria: 'ESTADO_PEDIDO_PROVEEDOR', clave: 'CANCELADO', valor: 'Cancelado', orden: null, descripcion: null },
  { categoria: 'ESTADO_RECEPCION', clave: 'BORRADOR', valor: 'Borrador', orden: null, descripcion: null },
  { categoria: 'ESTADO_RECEPCION', clave: 'CONFIRMADA', valor: 'Confirmada', orden: null, descripcion: null },
  { categoria: 'ESTADO_RECEPCION', clave: 'CANCELADA', valor: 'Cancelada', orden: null, descripcion: null },
  { categoria: 'CANAL_PEDIDO_CLIENTE', clave: 'ENCARGO', valor: 'Encargo', orden: 1, descripcion: 'Venta ligada a un proyecto/encargo de cliente.' },
  { categoria: 'CANAL_PEDIDO_CLIENTE', clave: 'FERIA', valor: 'Feria', orden: 2, descripcion: 'Venta directa en feria o mercado, sin proyecto previo.' },
  { categoria: 'CANAL_PEDIDO_CLIENTE', clave: 'TIENDA', valor: 'Tienda', orden: 3, descripcion: 'Venta directa en tienda, sin proyecto previo.' },
  { categoria: 'ESTADO_PEDIDO_CLIENTE', clave: 'BORRADOR', valor: 'Borrador', orden: null, descripcion: null },
  { categoria: 'ESTADO_PEDIDO_CLIENTE', clave: 'CONFIRMADO', valor: 'Confirmado', orden: null, descripcion: null },
  { categoria: 'ESTADO_PEDIDO_CLIENTE', clave: 'ENTREGADO_PARCIAL', valor: 'Entregado parcial', orden: null, descripcion: null },
  { categoria: 'ESTADO_PEDIDO_CLIENTE', clave: 'ENTREGADO_COMPLETO', valor: 'Entregado completo', orden: null, descripcion: null },
  { categoria: 'ESTADO_PEDIDO_CLIENTE', clave: 'CANCELADO', valor: 'Cancelado', orden: null, descripcion: null },
  { categoria: 'ESTADO_ENTREGA', clave: 'BORRADOR', valor: 'Borrador', orden: null, descripcion: null },
  { categoria: 'ESTADO_ENTREGA', clave: 'CONFIRMADA', valor: 'Confirmada', orden: null, descripcion: null },
  { categoria: 'ESTADO_ENTREGA', clave: 'CANCELADA', valor: 'Cancelada', orden: null, descripcion: null },
  { categoria: 'PERIODICIDAD_CONTRATO', clave: 'MENSUAL', valor: 'Mensual', orden: 1, descripcion: null },
  { categoria: 'PERIODICIDAD_CONTRATO', clave: 'ANUAL', valor: 'Anual', orden: 2, descripcion: null },
  { categoria: 'PERIODICIDAD_CONTRATO', clave: 'UNICO', valor: 'Único', orden: 3, descripcion: null },
  { categoria: 'MODALIDAD_PAGO', clave: 'MONETARIO', valor: 'Monetario', orden: 1, descripcion: null },
  { categoria: 'MODALIDAD_PAGO', clave: 'INTERCAMBIO', valor: 'Intercambio', orden: 2, descripcion: 'Contraprestación no monetaria (en especie, colaboración).' },
  { categoria: 'MODALIDAD_PAGO', clave: 'MIXTO', valor: 'Mixto', orden: 3, descripcion: 'Parte monetaria, parte en especie.' },
  { categoria: 'MODALIDAD_PAGO', clave: 'CESION_SOCIAL', valor: 'Cesión social', orden: 4, descripcion: 'Sin contraprestación, por criterio de impacto social.' },
  { categoria: 'ESTADO_CONTRATO_SERVICIO', clave: 'BORRADOR', valor: 'Borrador', orden: null, descripcion: null },
  { categoria: 'ESTADO_CONTRATO_SERVICIO', clave: 'ACTIVO', valor: 'Activo', orden: null, descripcion: null },
  { categoria: 'ESTADO_CONTRATO_SERVICIO', clave: 'PAUSADO', valor: 'Pausado', orden: null, descripcion: null },
  { categoria: 'ESTADO_CONTRATO_SERVICIO', clave: 'FINALIZADO', valor: 'Finalizado', orden: null, descripcion: null },
  { categoria: 'ESTADO_CONTRATO_SERVICIO', clave: 'CANCELADO', valor: 'Cancelado', orden: null, descripcion: null },
  { categoria: 'ORIGEN_OPORTUNIDAD', clave: 'PROSPECCION_WEB', valor: 'Prospección web', orden: 1, descripcion: null },
  { categoria: 'ORIGEN_OPORTUNIDAD', clave: 'FERIA', valor: 'Feria', orden: 2, descripcion: null },
  { categoria: 'ORIGEN_OPORTUNIDAD', clave: 'REFERENCIA', valor: 'Referencia', orden: 3, descripcion: null },
  { categoria: 'ORIGEN_OPORTUNIDAD', clave: 'ENTRANTE', valor: 'Entrante', orden: 4, descripcion: null },
  { categoria: 'AMBITO_OPORTUNIDAD', clave: 'RURAL', valor: 'Rural', orden: 1, descripcion: null },
  { categoria: 'AMBITO_OPORTUNIDAD', clave: 'CULTURAL', valor: 'Cultural', orden: 2, descripcion: null },
  { categoria: 'AMBITO_OPORTUNIDAD', clave: 'SOCIAL', valor: 'Social', orden: 3, descripcion: null },
  { categoria: 'AMBITO_OPORTUNIDAD', clave: 'VOLUNTARIADO', valor: 'Voluntariado', orden: 4, descripcion: null },
  { categoria: 'AMBITO_OPORTUNIDAD', clave: 'OTRO', valor: 'Otro', orden: 5, descripcion: null },
  { categoria: 'TIPO_OPORTUNIDAD', clave: 'PRODUCTO', valor: 'Producto', orden: 1, descripcion: null },
  { categoria: 'TIPO_OPORTUNIDAD', clave: 'SERVICIO_SOFTWARE', valor: 'Servicio de software', orden: 2, descripcion: null },
  { categoria: 'ESTADO_OPORTUNIDAD', clave: 'IDENTIFICADA', valor: 'Identificada', orden: 1, descripcion: null },
  { categoria: 'ESTADO_OPORTUNIDAD', clave: 'CONTACTADO', valor: 'Contactado', orden: 2, descripcion: null },
  { categoria: 'ESTADO_OPORTUNIDAD', clave: 'PROPUESTA_ENVIADA', valor: 'Propuesta enviada', orden: 3, descripcion: null },
  { categoria: 'ESTADO_OPORTUNIDAD', clave: 'GANADA', valor: 'Ganada', orden: 4, descripcion: null },
  { categoria: 'ESTADO_OPORTUNIDAD', clave: 'PERDIDA', valor: 'Perdida', orden: 5, descripcion: null },
  { categoria: 'SECTOR_OBJETIVO', clave: 'RURAL', valor: 'Rural', orden: 1, descripcion: 'Sector considerado encaje prioritario para La Troballa.' },
  { categoria: 'SECTOR_OBJETIVO', clave: 'CULTURAL', valor: 'Cultural', orden: 2, descripcion: 'Sector considerado encaje prioritario para La Troballa.' },
  { categoria: 'SECTOR_OBJETIVO', clave: 'SOCIAL', valor: 'Social', orden: 3, descripcion: 'Sector considerado encaje prioritario para La Troballa.' },
  { categoria: 'SECTOR_OBJETIVO', clave: 'VOLUNTARIADO', valor: 'Voluntariado', orden: 4, descripcion: 'Sector considerado encaje prioritario para La Troballa.' },
  { categoria: 'FASE_PRODUCCION', clave: 'PREPRODUCCION', valor: 'Preproducción', orden: null, descripcion: null },
  { categoria: 'FASE_PRODUCCION', clave: 'PRODUCCION', valor: 'Producción', orden: null, descripcion: null },
  { categoria: 'FASE_PRODUCCION', clave: 'POSTPRODUCCION', valor: 'Postproducción', orden: null, descripcion: null },
  { categoria: 'ENTIDAD_HORARIO', clave: 'RECURSO', valor: 'Recurso', orden: null, descripcion: null },
  { categoria: 'ENTIDAD_HORARIO', clave: 'PERSONA_EQUIPO', valor: 'Persona/Equipo', orden: null, descripcion: null },
  { categoria: 'DIA_SEMANA', clave: 'LUNES', valor: 'Lunes', orden: null, descripcion: null },
  { categoria: 'DIA_SEMANA', clave: 'MARTES', valor: 'Martes', orden: null, descripcion: null },
  { categoria: 'DIA_SEMANA', clave: 'MIERCOLES', valor: 'Miércoles', orden: null, descripcion: null },
  { categoria: 'DIA_SEMANA', clave: 'JUEVES', valor: 'Jueves', orden: null, descripcion: null },
  { categoria: 'DIA_SEMANA', clave: 'VIERNES', valor: 'Viernes', orden: null, descripcion: null },
  { categoria: 'DIA_SEMANA', clave: 'SABADO', valor: 'Sábado', orden: null, descripcion: null },
  { categoria: 'DIA_SEMANA', clave: 'DOMINGO', valor: 'Domingo', orden: null, descripcion: null },
  { categoria: 'ENTIDAD_PRESUPUESTO', clave: 'CAMPANA', valor: 'Campaña', orden: null, descripcion: null },
  { categoria: 'ENTIDAD_PRESUPUESTO', clave: 'PROYECTO', valor: 'Proyecto', orden: null, descripcion: null },
  { categoria: 'ENTIDAD_PRESUPUESTO', clave: 'PRODUCTO', valor: 'Producto', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_PRESUPUESTO', clave: 'MATERIALES', valor: 'Materiales', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_PRESUPUESTO', clave: 'RECURSOS', valor: 'Recursos', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_PRESUPUESTO', clave: 'ACTIVIDAD', valor: 'Actividad', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_PRESUPUESTO', clave: 'OTROS', valor: 'Otros', orden: null, descripcion: null },
  { categoria: 'TIPO_FUENTE_FINANCIACION', clave: 'SUBVENCION', valor: 'Subvención', orden: null, descripcion: null },
  { categoria: 'TIPO_FUENTE_FINANCIACION', clave: 'DEPARTAMENTO', valor: 'Departamento', orden: null, descripcion: null },
  { categoria: 'TIPO_FUENTE_FINANCIACION', clave: 'CLIENTE', valor: 'Cliente', orden: null, descripcion: null },
  { categoria: 'TIPO_FUENTE_FINANCIACION', clave: 'DONACION', valor: 'Donación', orden: null, descripcion: null },
  { categoria: 'TIPO_FUENTE_FINANCIACION', clave: 'OTRO', valor: 'Otro', orden: null, descripcion: null },
  { categoria: 'ESTADO_FUENTE_FINANCIACION', clave: 'SOLICITADA', valor: 'Solicitada', orden: null, descripcion: null },
  { categoria: 'ESTADO_FUENTE_FINANCIACION', clave: 'CONCEDIDA', valor: 'Concedida', orden: null, descripcion: null },
  { categoria: 'ESTADO_FUENTE_FINANCIACION', clave: 'PENDIENTE_COBRO', valor: 'Pendiente de cobro', orden: null, descripcion: null },
  { categoria: 'ESTADO_FUENTE_FINANCIACION', clave: 'COBRADA', valor: 'Cobrada', orden: null, descripcion: null },
  { categoria: 'ESTADO_FUENTE_FINANCIACION', clave: 'RECHAZADA', valor: 'Rechazada', orden: null, descripcion: null },
  { categoria: 'MODO_COSTE_RECURSO', clave: 'AMORTIZACION', valor: 'Amortización', orden: null, descripcion: null },
  { categoria: 'MODO_COSTE_RECURSO', clave: 'PERIODICO', valor: 'Periódico', orden: null, descripcion: null },
  { categoria: 'MODO_COSTE_RECURSO', clave: 'SIN_COSTE', valor: 'Sin coste', orden: null, descripcion: null },
  { categoria: 'PERIODICIDAD_COSTE', clave: 'MENSUAL', valor: 'Mensual', orden: null, descripcion: null },
  { categoria: 'PERIODICIDAD_COSTE', clave: 'ANUAL', valor: 'Anual', orden: null, descripcion: null },
  { categoria: 'ENTIDAD_COSTE', clave: 'CAMPANA', valor: 'Campaña', orden: null, descripcion: null },
  { categoria: 'ENTIDAD_COSTE', clave: 'PROYECTO', valor: 'Proyecto', orden: null, descripcion: null },
  { categoria: 'ENTIDAD_COSTE', clave: 'PRODUCTO', valor: 'Producto', orden: null, descripcion: null },
  { categoria: 'ENTIDAD_COSTE', clave: 'RECURSO', valor: 'Recurso', orden: null, descripcion: null },
  { categoria: 'ESTADO_COSTE', clave: 'PREVISTO', valor: 'Previsto', orden: null, descripcion: null },
  { categoria: 'ESTADO_COSTE', clave: 'CONFIRMADO', valor: 'Confirmado', orden: null, descripcion: null },
  { categoria: 'ESTADO_COSTE', clave: 'PAGADO', valor: 'Pagado', orden: null, descripcion: null },
  { categoria: 'ESTADO_COMPETENCIA', clave: 'ACTIVA', valor: 'Activa', orden: null, descripcion: null },
  { categoria: 'ESTADO_COMPETENCIA', clave: 'INACTIVA', valor: 'Inactiva', orden: null, descripcion: null },
  { categoria: 'NIVEL_COMPETENCIA', clave: 'BASICO', valor: 'Básico', orden: null, descripcion: null },
  { categoria: 'NIVEL_COMPETENCIA', clave: 'INTERMEDIO', valor: 'Intermedio', orden: null, descripcion: null },
  { categoria: 'NIVEL_COMPETENCIA', clave: 'AVANZADO', valor: 'Avanzado', orden: null, descripcion: null },
  { categoria: 'TIPO_CONVOCATORIA', clave: 'SUBVENCION_PUBLICA', valor: 'Subvención pública', orden: null, descripcion: null },
  { categoria: 'TIPO_CONVOCATORIA', clave: 'PREMIO', valor: 'Premio', orden: null, descripcion: null },
  { categoria: 'TIPO_CONVOCATORIA', clave: 'CONCURSO', valor: 'Concurso', orden: null, descripcion: null },
  { categoria: 'TIPO_CONVOCATORIA', clave: 'AYUDA_PRIVADA', valor: 'Ayuda privada', orden: null, descripcion: null },
  { categoria: 'TIPO_CONVOCATORIA', clave: 'DONACION', valor: 'Donación', orden: null, descripcion: null },
  { categoria: 'TIPO_CONVOCATORIA', clave: 'OTRO', valor: 'Otro', orden: null, descripcion: null },
  { categoria: 'ESTADO_CONVOCATORIA', clave: 'ABIERTA', valor: 'Abierta', orden: null, descripcion: null },
  { categoria: 'ESTADO_CONVOCATORIA', clave: 'CERRADA', valor: 'Cerrada', orden: null, descripcion: null },
  { categoria: 'ESTADO_CONVOCATORIA', clave: 'PRESENTADA', valor: 'Presentada', orden: null, descripcion: null },
  { categoria: 'ESTADO_CONVOCATORIA', clave: 'RESUELTA', valor: 'Resuelta', orden: null, descripcion: null },
  { categoria: 'ESTADO_CONVOCATORIA', clave: 'DESCARTADA', valor: 'Descartada', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_IMPACTO', clave: 'SOCIAL', valor: 'Social', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_IMPACTO', clave: 'ECOLOGICO', valor: 'Ecológico', orden: null, descripcion: null },
  { categoria: 'CATEGORIA_IMPACTO', clave: 'ECONOMICO', valor: 'Económico', orden: null, descripcion: null },
  { categoria: 'NIVEL_DATO', clave: 'OPERATIVO', valor: 'Operativo', orden: null, descripcion: null },
  { categoria: 'NIVEL_DATO', clave: 'PILOTO', valor: 'Piloto', orden: null, descripcion: null },
  { categoria: 'NIVEL_DATO', clave: 'AUDITORIA', valor: 'Auditoría', orden: null, descripcion: null },
  { categoria: 'PERFIL_ESCENARIO', clave: 'IDEAL', valor: 'Ideal', orden: 1, descripcion: 'Sin fricción deliberada -- comportamiento actual, todo sale según lo previsto.' },
  { categoria: 'PERFIL_ESCENARIO', clave: 'COMPLICACIONES_TIPICAS', valor: 'Con complicaciones típicas', orden: 2, descripcion: 'Fricción moderada y realista en varios ejes.' },
  { categoria: 'PERFIL_ESCENARIO', clave: 'CRISIS_CONTROLADA', valor: 'Crisis controlada', orden: 3, descripcion: 'Fricción intensa en varios ejes a la vez.' },
  { categoria: 'PERFIL_ESCENARIO', clave: 'PERSONALIZADO', valor: 'Personalizado', orden: 4, descripcion: 'La intensidad de cada eje se decide una por una, no sigue un perfil predefinido.' },
  { categoria: 'INTENSIDAD_ESCENARIO', clave: 'NINGUNA', valor: 'Ninguna', orden: 1, descripcion: null },
  { categoria: 'INTENSIDAD_ESCENARIO', clave: 'OCASIONAL', valor: 'Ocasional', orden: 2, descripcion: null },
  { categoria: 'INTENSIDAD_ESCENARIO', clave: 'FRECUENTE', valor: 'Frecuente', orden: 3, descripcion: null },
  { categoria: 'ESTADO_ESCENARIO', clave: 'BORRADOR', valor: 'Borrador', orden: 1, descripcion: null },
  { categoria: 'ESTADO_ESCENARIO', clave: 'ACTIVO', valor: 'Activo', orden: 2, descripcion: 'El que se usa para generar los próximos PROMPT_IA.txt de Importación masiva.' },
  { categoria: 'ESTADO_ESCENARIO', clave: 'ARCHIVADO', valor: 'Archivado', orden: 3, descripcion: null }
]);
